// Code generated by protoc-gen-gogo.
// source: job_desc.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type JobDescriptor_JobState int32

const (
	JobDescriptor_New       JobDescriptor_JobState = 0
	JobDescriptor_Created   JobDescriptor_JobState = 1
	JobDescriptor_Running   JobDescriptor_JobState = 2
	JobDescriptor_Completed JobDescriptor_JobState = 3
	JobDescriptor_Failed    JobDescriptor_JobState = 4
	JobDescriptor_Aborted   JobDescriptor_JobState = 5
	JobDescriptor_Unknown   JobDescriptor_JobState = 6
)

var JobDescriptor_JobState_name = map[int32]string{
	0: "New",
	1: "Created",
	2: "Running",
	3: "Completed",
	4: "Failed",
	5: "Aborted",
	6: "Unknown",
}
var JobDescriptor_JobState_value = map[string]int32{
	"New":       0,
	"Created":   1,
	"Running":   2,
	"Completed": 3,
	"Failed":    4,
	"Aborted":   5,
	"Unknown":   6,
}

func (x JobDescriptor_JobState) String() string {
	return proto1.EnumName(JobDescriptor_JobState_name, int32(x))
}
func (JobDescriptor_JobState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorJobDesc, []int{0, 0}
}

type JobDescriptor struct {
	Uuid      string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State     JobDescriptor_JobState `protobuf:"varint,3,opt,name=state,proto3,enum=proto.JobDescriptor_JobState" json:"state,omitempty"`
	RootTask  *TaskDescriptor        `protobuf:"bytes,4,opt,name=root_task,json=rootTask" json:"root_task,omitempty"`
	OutputIds [][]byte               `protobuf:"bytes,5,rep,name=output_ids,json=outputIds" json:"output_ids,omitempty"`
}

func (m *JobDescriptor) Reset()                    { *m = JobDescriptor{} }
func (m *JobDescriptor) String() string            { return proto1.CompactTextString(m) }
func (*JobDescriptor) ProtoMessage()               {}
func (*JobDescriptor) Descriptor() ([]byte, []int) { return fileDescriptorJobDesc, []int{0} }

func (m *JobDescriptor) GetRootTask() *TaskDescriptor {
	if m != nil {
		return m.RootTask
	}
	return nil
}

func init() {
	proto1.RegisterType((*JobDescriptor)(nil), "proto.JobDescriptor")
	proto1.RegisterEnum("proto.JobDescriptor_JobState", JobDescriptor_JobState_name, JobDescriptor_JobState_value)
}
func (m *JobDescriptor) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *JobDescriptor) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uuid) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintJobDesc(data, i, uint64(len(m.Uuid)))
		i += copy(data[i:], m.Uuid)
	}
	if len(m.Name) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintJobDesc(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if m.State != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintJobDesc(data, i, uint64(m.State))
	}
	if m.RootTask != nil {
		data[i] = 0x22
		i++
		i = encodeVarintJobDesc(data, i, uint64(m.RootTask.Size()))
		n1, err := m.RootTask.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.OutputIds) > 0 {
		for _, b := range m.OutputIds {
			data[i] = 0x2a
			i++
			i = encodeVarintJobDesc(data, i, uint64(len(b)))
			i += copy(data[i:], b)
		}
	}
	return i, nil
}

func encodeFixed64JobDesc(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32JobDesc(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintJobDesc(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *JobDescriptor) Size() (n int) {
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovJobDesc(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovJobDesc(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovJobDesc(uint64(m.State))
	}
	if m.RootTask != nil {
		l = m.RootTask.Size()
		n += 1 + l + sovJobDesc(uint64(l))
	}
	if len(m.OutputIds) > 0 {
		for _, b := range m.OutputIds {
			l = len(b)
			n += 1 + l + sovJobDesc(uint64(l))
		}
	}
	return n
}

func sovJobDesc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozJobDesc(x uint64) (n int) {
	return sovJobDesc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *JobDescriptor) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJobDesc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: JobDescriptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: JobDescriptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJobDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJobDesc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJobDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJobDesc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJobDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.State |= (JobDescriptor_JobState(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJobDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJobDesc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RootTask == nil {
				m.RootTask = &TaskDescriptor{}
			}
			if err := m.RootTask.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputIds", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJobDesc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthJobDesc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputIds = append(m.OutputIds, make([]byte, postIndex-iNdEx))
			copy(m.OutputIds[len(m.OutputIds)-1], data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJobDesc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthJobDesc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipJobDesc(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowJobDesc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJobDesc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJobDesc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthJobDesc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowJobDesc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipJobDesc(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthJobDesc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowJobDesc   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorJobDesc = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8e, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x29, 0xa5, 0x40, 0x07, 0xc1, 0x66, 0x13, 0x93, 0x86, 0x04, 0x42, 0x38, 0x71, 0x11,
	0x12, 0x78, 0x02, 0xc5, 0x98, 0xe8, 0xc1, 0x43, 0xd5, 0x33, 0xe9, 0xd2, 0x5a, 0x2b, 0x74, 0xa7,
	0xd9, 0xee, 0x86, 0x57, 0xf1, 0xee, 0xcb, 0x78, 0xf4, 0x11, 0x8c, 0xbe, 0x88, 0x3b, 0x5b, 0x8d,
	0x7a, 0xd8, 0xf4, 0xff, 0xbf, 0xf9, 0xff, 0xe9, 0xc0, 0xe0, 0x09, 0xf9, 0x26, 0x49, 0xab, 0xed,
	0xbc, 0x94, 0xa8, 0x90, 0x79, 0xf6, 0x33, 0x3c, 0xcd, 0x72, 0xf5, 0xa8, 0xf9, 0x7c, 0x8b, 0xc5,
	0x22, 0xc3, 0x0c, 0x17, 0x16, 0x73, 0xfd, 0x60, 0x9d, 0x35, 0x56, 0xd5, 0xad, 0xe1, 0xb1, 0x8a,
	0xab, 0xdd, 0x9f, 0x35, 0xd3, 0x97, 0x26, 0xf4, 0xaf, 0x91, 0x5f, 0x18, 0x22, 0xf3, 0x52, 0xa1,
	0x64, 0x0c, 0x5a, 0x5a, 0xe7, 0x49, 0xe8, 0x4c, 0x9c, 0x99, 0x1f, 0x59, 0x4d, 0x4c, 0xc4, 0x45,
	0x1a, 0x36, 0x6b, 0x46, 0x9a, 0xad, 0xc0, 0xab, 0x54, 0xac, 0xd2, 0xd0, 0x35, 0x70, 0xb0, 0x1c,
	0xd5, 0x0b, 0xe7, 0xff, 0x96, 0x91, 0xbb, 0xa5, 0x50, 0x54, 0x67, 0xd9, 0x12, 0x7c, 0x89, 0xa8,
	0x36, 0x74, 0x46, 0xd8, 0x32, 0xc5, 0xde, 0xf2, 0xe4, 0xbb, 0x78, 0x67, 0xd0, 0x6f, 0x33, 0xea,
	0x52, 0x8e, 0x18, 0x1b, 0x01, 0xa0, 0x56, 0xa5, 0x56, 0x9b, 0x3c, 0xa9, 0x42, 0x6f, 0xe2, 0xce,
	0x8e, 0x22, 0xbf, 0x26, 0x57, 0x49, 0x35, 0xe5, 0xd0, 0xfd, 0xf9, 0x0b, 0xeb, 0x80, 0x7b, 0x93,
	0x1e, 0x82, 0x06, 0xeb, 0x41, 0x67, 0x2d, 0x53, 0x83, 0x92, 0xc0, 0x21, 0x13, 0x69, 0x21, 0x72,
	0x91, 0x05, 0x4d, 0xd6, 0x07, 0x7f, 0x8d, 0x45, 0xb9, 0x4f, 0x69, 0xe6, 0x32, 0x80, 0xf6, 0x65,
	0x9c, 0xef, 0x8d, 0x6e, 0x51, 0xee, 0x8c, 0xa3, 0xa4, 0x81, 0x47, 0xe6, 0x5e, 0xec, 0x04, 0x1e,
	0x44, 0xd0, 0x3e, 0x0f, 0x5e, 0x3f, 0xc6, 0xce, 0x9b, 0x79, 0xef, 0xe6, 0x3d, 0x7f, 0x8e, 0x1b,
	0xbc, 0x6d, 0x8f, 0x5e, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x0b, 0x39, 0x5b, 0x97, 0x01,
	0x00, 0x00,
}
